baseURL = 'https://georgeSleen.github.io'
DefaultContentLanguage = "en"
title = "George Sleen"
# When using theme as hugo module
theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Engineering Physics Student at UBC"
  mainSections = ["projects"]
  logo = "img/profile-picture.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = false
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = false
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

# Directory definition

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "projects"
    weight = 2

[[menu.main]]
    name = "Resume"
    url = "resume"
    weight = 3

[[menu.main]]
    identifier = "about"
    name = "about"
    weight = 4

[[menu.main]]
    parent = "about"
    name = "About Me"
    url = "about/about-me"
    weight = 1

[[menu.main]]
    parent = "about"
    name = "Courses"
    url = "about/courses"
    weight = 2

# Contact information

[Params.author]
    # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
    name = "George Sleen"
    website = "georgeSleen.github.io"
    email = "gsleen@gmail.com"
    github = "github.com/georgeSleen"
    linkedin = "george-sleen"